apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: user-image
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
      imagePullSecrets:
        - name: gitlab-registry